/**
 * WebRTC / DataChannel protocol.
 *
 * Two DataChannels are negotiated between peers:
 *
 *  - `control` : ordered + reliable, JSON text frames. Small messages only
 *                (file lists, transfer handshakes, cancel, ping/pong).
 *  - `file`    : ordered + reliable, binary frames. 64 KB chunks of file data.
 *
 * Splitting them matters: a 64 KB binary frame cannot head-of-line block a
 * "cancel" or "file-list" request, because they travel on different channels.
 *
 * The cost of splitting them is easy to forget: **two channels are two
 * independent ordered streams with no ordering between them.** `transfer-done`
 * rides the control channel while the payload rides the file channel, so it
 * routinely overtakes bytes the sender has already queued — and always does when
 * the sender is pushing fast enough to have a backlog. A receiver that treats
 * `transfer-done` as "the bytes are all here" fails large transfers at whatever
 * power-of-two boundary the backlog sat at. `ChunkReceiver.complete()` therefore
 * treats it as a byte count to wait for, never as proof of arrival.
 */

import type { FileCategory } from "./files";
import type { DeviceType } from "./signaling";

export const DATA_PROTOCOL_VERSION = 1;

export const CONTROL_CHANNEL_LABEL = "sharego-control";
export const FILE_CHANNEL_LABEL = "sharego-file";

/* ------------------------------------------------------------------ */
/* Binary framing (file channel)                                       */
/* ------------------------------------------------------------------ */

export const FRAME_KIND_CHUNK = 1;

/**
 * Layout of a binary frame on the `file` channel:
 *
 * ```
 *  0        1                    5                    9
 *  +--------+--------------------+--------------------+-----------------+
 *  | kind   | transferId (u32)   | sequence (u32)     | payload bytes  |
 *  +--------+--------------------+--------------------+-----------------+
 * ```
 *
 * `transferId` is generated by the *sender* and is unique within that peer's
 * session, which is all the receiver needs to route bytes to the right
 * download. Using a fixed 9 byte header instead of JSON-per-chunk keeps
 * per-chunk overhead at ~0.01% for 64 KB chunks.
 */
export const FRAME_HEADER_BYTES = 9;

/* ------------------------------------------------------------------ */
/* Control protocol (control channel, JSON)                           */
/* ------------------------------------------------------------------ */

export type TransferPurpose = "preview" | "download";

export type TransferErrorCode =
  | "unknown-file"
  | "busy"
  | "too-many"
  | "io-error"
  | "cancelled"
  | "protocol-error";

/** Sent right after the channels open; lets us detect version mismatches. */
export interface ControlHello {
  type: "control-hello";
  protocol: number;
  deviceName: string;
}

/** "My shared file list changed, ask again if you need it." */
export interface ControlFilesChanged {
  type: "files-changed";
}

export interface ControlFileListRequest {
  type: "file-list-request";
}

export interface ControlFileList {
  type: "file-list";
  files: SharedFileMetaLite[];
}

/**
 * Trimmed metadata for the wire. Deliberately a subset of `SharedFileMeta`
 * with hard length limits so a hostile peer cannot push megabyte-long strings
 * into our React state.
 */
export interface SharedFileMetaLite {
  fileId: string;
  name: string;
  size: number;
  mimeType: string;
  lastModified: number;
  path: string | null;
  category: FileCategory;
}

/**
 * Ask the peer to start streaming `[offset, offset + length)` of a file.
 * The sender replies with `transfer-done` when the range is fully written, or
 * `transfer-error`.
 *
 * `offset`/`length` are what make this a *range* protocol: today we always ask
 * for `[0, size)`, but a future desktop companion (or an HTTP fallback) can ask
 * for a single byte window to implement true seeking in media players.
 */
export interface ControlFileRequest {
  type: "file-request";
  transferId: number;
  fileId: string;
  purpose: TransferPurpose;
  offset: number;
  length: number;
}

export interface ControlTransferDone {
  type: "transfer-done";
  transferId: number;
  bytesSent: number;
}

export interface ControlTransferError {
  type: "transfer-error";
  transferId: number;
  code: TransferErrorCode;
  message: string;
}

export interface ControlCancelTransfer {
  type: "cancel-transfer";
  transferId: number;
}

export interface ControlPing {
  type: "control-ping";
  at: number;
}

export interface ControlPong {
  type: "control-pong";
  at: number;
}

export type ControlMessage =
  | ControlHello
  | ControlFilesChanged
  | ControlFileListRequest
  | ControlFileList
  | ControlFileRequest
  | ControlTransferDone
  | ControlTransferError
  | ControlCancelTransfer
  | ControlPing
  | ControlPong;

/* ------------------------------------------------------------------ */
/* Peer lifecycle                                                      */
/* ------------------------------------------------------------------ */

export type PeerState =
  /** Peer is visible in the device list, nothing negotiated yet. */
  | "idle"
  /** We sent a connection request and are waiting for accept/reject. */
  | "requesting"
  /** A request is on screen on the other device. */
  | "incoming"
  /** Offer/answer/ICE in flight. */
  | "negotiating"
  /** DataChannels are open. Files can flow. */
  | "connected"
  /** Peer went quiet (tab throttled, network hiccup). */
  | "disconnected"
  /** ICE gave up. */
  | "failed"
  /** Closed on purpose by either side. */
  | "closed";

export interface PeerSnapshot {
  deviceId: string;
  deviceName: string;
  deviceType: DeviceType;
  state: PeerState;
  /** Populated when `state === "failed" | "closed"` with a human message. */
  error: string | null;
  connectedAt: number | null;
}

export interface IncomingRequestSnapshot {
  requestId: string;
  deviceId: string;
  deviceName: string;
  deviceType: DeviceType;
  receivedAt: number;
  expiresAt: number;
}
